spring.application.name=jobportal

spring.datasource.url=jdbc:postgresql://localhost:5432/Jobportal_db
spring.datasource.username=postgres
spring.datasource.password=vishal

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#upload file
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
